// scripts/csv-to-seed.js
const fs = require('fs');
const path = require('path');

// Lee el CSV y genera el archivo de seed
const csvData = `
DESCRIPCIÓN	SERIE	CATEGORIA	PROCESO	STATUS	INVENTARIO
6010 FR7A CAPUCHA DE ALGODÓN	S/N	EPP	OPERACIONES	EN OPERACIÓN	1
ABRAZADERA PLÁSTICO RÁPIDA MACHO/HEMBRA TRUPER 1/2"	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	10
ABRAZADERA PLÁSTICO RÁPIDA MACHO/HEMBRA TRUPER 3/4" - 5/8"	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	2
ACIDO CÍTRICO CLR DESCALSIFICANTE INDUSTRIAL (828 ML)	S/N	ALIMENTICIA	OPERACIONES	EN OPERACIÓN	1
ADAPTADOR P/MANIFOLD	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	5
ADAPTADOR P/PUNTAS	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
ANALIZADOR DE GASES BACHARACH 0024-8512	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
ANALIZADOR PH/TDS/SAL/TEMP AGUA	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
ANEMOMETRO DIGITAL BENETECH	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
ARCO PARA SEGUETA PRETUL CON SEGUETA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
ARNES CON LINEA DE VIDA Y AMORT AMARILLO	S/N	EPP	OPERACIONES	EN OPERACIÓN	8
ARNES CON LINEA DE VIDA Y AMORT ROJO	S/N	EPP	OPERACIONES	EN OPERACIÓN	2
ARNES TIPO CINTURON CON 2 ARGOLLAS	S/N	EPP	OPERACIONES	EN OPERACIÓN	2
ASPIRADORA P/CARR KOBLENZ	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
ASPIRADORA STANLEY	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
AUTOCLE SURE BILT 43 PZAS	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
AVELLANADOR 4 MEDIDAS	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
AVELLANADOR 5/8" 3/4" 7/8" 1 1/8" GB	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
AVELLANADOR 7 MEDIDAS	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
AVELLANADOR 7 MEDIDAS TRUPER 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
BANDA DE SUJECIÓN SIN MATRACA AMARILLO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
BANDA DE SUJECIÓN SIN MATRACA NARANJA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
BANDERIN DE SEGURIDAD CON REFLEJANTE	S/N	EQUIPOS DE SEGURIDAD	OPERACIONES	EN OPERACIÓN	3
BARILLA SOLDADURA DE ALUMINIO	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	
BARILLA SOLDADURA DE PLATA	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	
BASCULA DIGITAL CARGA Y RECUP REF ELITECH	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BATERIA DEWALT LITHIUM ION N576585	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BATERIA DEWALT LITHIUM ION N830732	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BATERIA PRETUL 20V	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	
BATERIA RYOBI 1.3 AMP	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BATERIA RYOBI 1.5 AMP	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BATERIAS M18 RED LITHIUM PARA TALADROS MILWAUKEE	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BATERIAS PRETUL 12V	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BOCASIERRA BI-METAL 1-3/4" Y MANDRIL TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BOLSA PROTECTORA P/LAVADO CASETTE	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BOLSA PROTECTORA P/LAVADO MINI SPLIT	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BOMBA DE TALADRO	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BOMBA DE VACIO AYCON AY-702	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BOMBA DE VACIO THORN	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BOMBA DE VACIO YELLOW JACKET	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
BOQ. PARA GAS BUTANO PORTATIL (LATA)	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BOQUILLA P/TANQUE DE NITROGENO C/ADAPTADOR PARA MANIFOLD	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BOQUILLA PARA LANZA HIDROLAVADORA RYOBI	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	25
BOQUILLA PARA SOPLETE DE GAS BUTANO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BOQUILLA PARA TANQUE DE NITROGENO 1 M3	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BOQUILLA PARA TANQUE DE NITROGENO 9 M3	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BOQUILLA PARA TURNER HT-802B	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
BROCASIERRA  1 1/4" HOL DOZER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA 1 1/2 BIMETAL Y MADRIL TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA 1-1/2" PRETUL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA 1-1/4" Y MANDRIL PRETUL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA 2" PRETUL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA 2-1/8" PRETUL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA BI-METAL 1" URREA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA BI-METAL 1-1/2" TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
BROCASIERRA BI-METAL 1-1/4" MILWAUKEE HOL DOZER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA BI-METAL 1-1/4" Y MANDRIL TRUPER 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA BI-METAL 2" TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA BI-METAL 2-1/4" TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA BI-METAL 2-1/8" TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA BI-METAL 3/4" Y MANDRIL TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
BROCASIERRA BI-METAL 7/8" TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CALAFATEADORA BIP	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CALAFATEADORA TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CALIBRADOR DIGITAL SURE BILT	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CANDADO DE SEGURIDAD 1 1/2" CON ETIQUETA	S/N	EQUIPOS DE SEGURIDAD	OPERACIONES	EN OPERACIÓN	4
CARGADOR CRAFTZMAN V20 2023 38-47	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
CARGADOR M18 Y M12 PARA EQUIPOS MILWAUKEE	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
CARGADOR PARA TALADROS DEWALT DCB1104	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	2
CASCO V-GARD MSA BLANCO	S/N	EPP	OPERACIONES	EN OPERACIÓN	5
CASCO V-GARD MSA BLANCO ALA ANCHA	S/N	EPP	OPERACIONES	EN OPERACIÓN	5
CHALECO DE MALLA CON REFLEJANTE NARANJA	S/N	EPP	OPERACIONES	EN OPERACIÓN	5
CHALECO REFLEJANTE AMARILLO	S/N	EPP	OPERACIONES	EN OPERACIÓN	2
CHALECO REFLEJANTE AZUL	S/N	EPP	OPERACIONES	EN OPERACIÓN	1
CHALECO REFLEJANTE ROJO	S/N	EPP	OPERACIONES	EN OPERACIÓN	1
CHALECO REFLEJANTE VERDE	S/N	EPP	OPERACIONES	EN OPERACIÓN	1
CINCEL CORTE FRIO 1/2	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	4
CINCEL CORTE FRIO 5/8	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CINCEL PLANO 1 9/16	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CINTA DE PRECAUCIÓN	S/N	EQUIPOS DE SEGURIDAD	OPERACIONES	EN OPERACIÓN	3
COMPRESORA DE AIRE MARCA SWEDISH HUSKY POWER ROJO	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
CONECTOR "Y" 3/4 META RECUBRIMIENTO TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
CONECTOR "Y" PLASTICO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
CONECTORES RÁPIDOS DE SEGURIDAD P/HIDRO HEMBRA TRUPER	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	2
CONEXIÓN "Y" PARA MANGUERAS 1/2	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CONEXIÓN HEMBRA PARA MANGUERA VARIAS	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	3
CONEXIÓN PLASTICO P/MANGUERA MACHO TRUPER	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	7
CONEXIÓN RÁPIDA SEGURIDAD P/HIDRO HEMBRA KARCHER	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	7
CONEXIÓN RÁPIDA SEGURIDAD P/HIDRO HEMBRA TRUPER	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	2
CORTA CABLES (AMARILLO)	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
CORTA PERNOS CP-18X	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CORTADOR DE TUBOS DE PLASTICO 1-5/8" 42MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
CORTATUBOS 1/8"-7/8" (3-22MM)	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CORTATUBOS 174-F 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CORTATUBOS PRETUL 1/8"-1 1/8"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CORTATUBOS SURTEK 350F 1/8"-1 1/8"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CORTATUBOS UNIWELD 1/8"-1 1/8" UTC702	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
CUBREBOCA N95	S/N	EPP	OPERACIONES	EN OPERACIÓN	1
CUBRENUCA DE ALTA VISIBILIDAD NARANJA	S/N	EPP	OPERACIONES	EN OPERACIÓN	2
CUBRENUCA DE ALTA VISIBILIDAD SR1040 MR SEGURIDAD AMARILLO	S/N	EPP	OPERACIONES	EN OPERACIÓN	10
CUERDA POLI P/TENDEDERO 3/16" COLOR AZUL 15.2M	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 1/4" 10 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 1/4" 11 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 1/4" 12 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 1/4" 13 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 1/4" 5 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 1/4" 5.5 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 1/4" 6 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 1/4" 7 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 1/4" 8 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 1/4" 9 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 3/8" 13 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 3/8" 14 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 3/8" 15 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 3/8" 16 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 3/8" 17 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 3/8" 18 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO ENTRADA 3/8" 19 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO LARGO ENTRADA 3/8" 16 MM 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DADO LARGO ENTRADA 3/8" 21 MM 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR 11 EN 1 COMERCIAL ELECTRIC	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
DESARMADOR AISLADO DE CRUZ B2 PH2 X 100 MANGO ROJO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR AISLADO PLANO A4 4 X 100 MANGO ROJO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR CORTO 2 EN 1	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
DESARMADOR CRUZ PRETUL 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR CRUZ STANLEY 65-252	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR CRUZ TRUPER MANGO COMFORT	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR CUBO 1/4" ACETATO TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
DESARMADOR DE CRUZ PH1 X 80 MM KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR DE CRUZ PH2 X 100MM KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR DE CUBO 5/16" TRUPER ACETATO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
DESARMADOR MULTIPUNTA TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR PARA DADOS KRONER 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR PLANO 1/4" X 6" PRETUL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR PLANO 3/8 X 12" TRUPER HER-235	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR PLANO 4 X 75 MM KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESARMADOR PLANO 5 X 100 MM KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESCALSIFICANTE RATIONAL 3 GALONES	S/N	ALIMENTICIA	OPERACIONES	EN OPERACIÓN	2 1/4
DESTORNILLADOR 4 EN 1 NEGRO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DESTORNILLADOR DE IMPACTO DEWALT 	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	2
DESTORNILLADOR Y TALADRO DE IMPACTO MILWAUKEE	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
DETECTOR DE FASES	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	2
DOBLA TUBO 1/2" - 1 1/2"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DOBLA TUBO 1/4" - 5/16" - 3/8"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DOBLA TUBO 3/4" - 3"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DOBLA TUBO 5/8" - 2 1/4"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
DOBLA TUBO 7/8" - 3 1/4"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
ENCENDEDOR DE CHISPA DE PEDERNAL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
ESCALERA 12 PELDAÑOS ALUMINIO TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
ESCALERA 24 PELDAÑOS FIBRA DE VIDRIO SURTEK	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
ESCALERA 24 PELDAÑOS METALICA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
ESCALERA 5 PELDAÑOS FIBRA DE VIDRIO ESCALUMEX	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
ESCALERA 7 PELDAÑOS FIBRA DE VIDRIO CUF RUM VERDE	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
ESCALERA AZUL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
ESCALERA DE BURRITO ALUMINIO TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
ESMERIL INALAMBRICO IRONHOOF	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
ESMERIL MILKWAUKEE	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
ESMERIL TRUPER	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
EXACTO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
EXACTO KRONER	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
EXTENSION 2" P/MATRACA DE 1/4"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
EXTENSION 3" P/MATRACA DE 1/4"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
EXTENSION 6" P/MATRACA DE 1/4"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
EXTENSIÓN LARGA HEXAGONAL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
EXTENSIÓN MEDIANADA P/MATRACA 1/4"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
EXTENSIÓN MEDIANADA P/MATRACA 3/8"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
EXTENSIONES HEXAGONALES PARA PUNTAS MAGNETICAS 1/4	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
EXTINTOR 2 KG	S/N	EQUIPOS DE SEGURIDAD	OPERACIONES	EN OPERACIÓN	4
EXTRACTOR DE PATA DE CABRA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
EXTRACTOR ENGRANE POLEA FORJA BRAZO	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
EXTRACTOR HIDRAULICO	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
FAJA 3XL	S/N	EPP	OPERACIONES	EN OPERACIÓN	1
FAJA DE SEGURIDAD ELASTICA REFORZADA SP1025 TALLA G MR	S/N	EPP	OPERACIONES	EN OPERACIÓN	1
FAJA ELASTICA REFORZADA SP1025 TALLA CH MR SEGURIDAD	S/N	EPP	OPERACIONES	EN OPERACIÓN	1
FAJA ELASTICA REFORZADA SP1025 TALLA EG MR SEGURIDAD	S/N	EPP	OPERACIONES	EN OPERACIÓN	2
FAJA SPECFIT 12500 XXL	S/N	EPP	OPERACIONES	EN OPERACIÓN	1
FILTRO DE AGUA PARA CONEXIÓN RÁPIDA	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	8
FILTRO DE AGUA PARA HIDROLAVADORA	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	3
FILTROS DESHIDRATADORES 1645 DANFOSS	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	
FLEXOMETRO DIGITAL DE LARGO ALCANCE JUEMEL	S/N	EQUIPO 	OPERACIONES	EN OPERACIÓN	1
FLEXOMETRO KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
FLEXOMETRO VARIAS MARCAS	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
FUMIGADOR 2L TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
FUMIGADOR FLO-MASTER 7.6 L	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
GRASERAS	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
GUANTES MILWAUKEE 48-22-8901	S/N	EPP	OPERACIONES	EN OPERACIÓN	8
HIDROLAVADORA FIXTEC	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
HIDROLAVADORA KARCHER COMPACTA 	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
HIDROLAVADORA KARCHER K4	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
HIDROLAVADORA KARCHER K4 PREMIUM	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	2
HIDROLAVADORA KARCHER PRO HD400	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	4
HIDROLAVADORA RYOBI	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	4
JGO 4 DESARMADORES DE PRECISIÓN KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JGO LLAVES TORX TRUPER (9 PZAS)	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JGO PUNTAS DE CRUZ Y PLANA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JGO PUNTAS DE SEGURIDAD/ESPECIALES	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JGO PUNTAS HEXAGONALES	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JGO PUNTAS TORX 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
JUEGO DE 13 LLAVES ALLEN MILIMETRICA TRUPER 13646	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JUEGO DE AVELLANADO CON CORTA TUBO Y EXPANSORES	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JUEGO DE AVELLANADOS DSZH	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JUEGO DE CINTA CON MATRACA AMARILLA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JUEGO DE LLAVES COMBINADAS SURE BILT 18 PZAS	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JGO D/MANOM C/MANGUERA Y SOPLETE P/OXICORTE C/ACETILENO Y BOQUILLA D/CORTE	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JGO DE MANOM C/MANGUERAS Y SOPLETE PARA OXICORTE C/ACETILENO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JGO DE MANOM C/MANGUERAS Y SOPLETE P/OXICORTE CON BUTANO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
JUGO 8 LLAVES ALLEN MILIMETRICAS KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
KIT PUNTAS P/MULTIMETRO 20 AMP	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	1
LANZA 250 MM P/KARCHER PRO HD 400	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
LENTES DE SEGURIDAD ANTI-EMPAÑO SAFETY	S/N	EPP	OPERACIONES	EN OPERACIÓN	2
LENTES DE SEGURIDAD DISEÑO LIGERO PRETUL	S/N	EPP	OPERACIONES	EN OPERACIÓN	2
LINEA DE VIDA SIN AMORTIGUADOR	S/N	EPP	OPERACIONES	EN OPERACIÓN	2
LLAVE COMBINADA 1 1/16" URREA 1234	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 1/2" CHROME VANADIUM 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 1/2" TRUPER LL-2016	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
LLAVE COMBINADA 1/4" MASTERGRIP	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 10 MM FOY	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 11/16" CHINA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 11/16" CRAFTMAN 14740	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 12 SIN CHROME VANADIUM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 12MM "PROTUL"	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 13 TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 15 MM CRAFTMAN	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 21 MM URREA 1221M	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 3/4" CRAFTSMAN 14741	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 3/8" CHINA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 3/8" FOY 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 3/8" HER-263	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 5/8" CRAFTMAN 1474	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 5/8" DROP FORGED STEEL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 5/8" LL-1220P PROTUL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 5/8" MARCA NO VISIBLE	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 9/16 PRETUL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE COMBINADA 9/16" DROP FORGED STEEL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE DE DOBLE MATRACA 3/16" 3/8" YELLOW JACKET 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE DE ESTRIAS 11/18" 3/4" URREA 1135	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE DE ESTRIAS 14-15 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE DE ESTRIAS 5/8" 11/16" URREA 8182	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE ESPAÑOLA 3/4" X 11/16" TRUPER LL-3035	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE ESPAÑOLA DROP FORGED 16-17 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE ESPAÑOLA ESTANDAR 3/4" X 11/16" TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE ESPAÑOLA ESTRIADA 11/16" X 3/4" URREA 1135	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE MATRACA 1/2" PRETUL ALTA SEGURIDAD	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE MATRACA 1/4" CRAFTSMAN 44807 ALTA SEGURIDAD	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE MATRACA 3/8" CRAFTSMAN 10031 ALTA SEGURIDAD	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE MATRACA 3/8" SIN MARCA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
LLAVE MATRACA DE SEGURIDAD 1/4" KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE MATRACA DE SEGURIDAD 3/8" KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LLAVE STILSON HEAVY DUTY 18	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LONA ROJA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
LUZ DE TRABAJO CON TRIPIE 2 LUCES LED 20 W	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	3
MAGUERA PARA R410 COLOR NEGRA	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	1
MANDIL DE CARNAZA 	S/N	EPP	OPERACIONES	EN OPERACIÓN	2
MANGUERAS PARA MANOMETRO CON VALVULAS DE PASO 	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	1
MANIFOLD ANALOGICO CON ESTUCHE NEGRO	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	2
MANIFOLD ANALOGICO YELLOW JACKET (01-02-03-04-05)	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	5
MANOMETRO ANALOGICO DE ALTA PRESIÓN ROJO	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	2
MANOMETRO ANALOGICO DE BAJA PRESIÓN AZUL	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
MANOMETRO DE MICRAS DIGITAL UEI	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
MANOMETRO DIGITAL	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	2
MARCO DE SOLERA P/SEGUETA TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
MARTILLO KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
MATRACA PARA BANDA DE SUJECIÓN AMARILLO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	6
MATRACA PARA BANDA DE SUJECIÓN NARANJA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
MOCHILA PARA HERRAMIENTA DEWALT	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	1
MOCHILA PARA HERRAMIENTA MILWAUKEE	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	1
MOCHILA PARA HERRAMIENTAS HUSKY	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	1
MULTI AMPERIMETRO DE GANCHO MARCA AVALY (01 - 02)	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	2
MULTI AMPERIMETRO DE GANCHO MARCA MASTFUYI (01)	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
MULTI AMPERIMETRO DE GANCHO MARCA UEI (01-02-03-04-05)	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	5
MULTI AMPERIMETRO UNI-T (01)	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
NIPLES RECTOS DE PLASTICO P/MANGUERA 1/2"	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	4
NIPLES RECTOS DE PLASTICO P/MANGUERA 933681	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	2
NIVEL DE GOTA KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
NIVEL DE GOTA VARIAS MARCAS	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PAQUETE 6 PZAS PEINES PARA SERPENTIN	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	1
PAQUETE CUCHILLAS P/EXACTO 10 PZAS KRONER	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	1
PAR DE GUANTES DE CARNAZA COLOR ROJO	S/N	EPP	OPERACIONES	EN OPERACIÓN	2
PATINES PARA CAJA PESADA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	8
PELACABLE Y CRIMPADOR AUTOMATICO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PERICA 8" PRETUL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PERICA DE 12" MARCA PRETUL	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
PERICA DE 8" 200 MM KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PERILLERO PLANO STANLEY	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PINZA DE ALICATE KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PINZA DE PUNTA KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PINZA DENTADA MARCA KLEIN TOOLS ROJA	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
PINZA MECANICA DE ALCANCE KRONER 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PINZA MECANICA KRONER 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PINZA MECANICA PRETUL 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PINZA PONCHADORA HIDRAULICA YQK-300 CON 30 PZAS	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PINZAS CORTA CABLES Y PELA CABLES 7" COMERCIAL ELECTRIC	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
PINZAS CORTE DIAGONAL 7" COMERCIAL ELECTRIC	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
PINZAS DE ELECTRICISTA 7" COMERCIAL ELECTRIC	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
PINZAS DE PUNTA 6" COMERCIAL ELECTRIC	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
PIRINOLA DE CRUZ PH2 X 38 MM KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PIRINOLA PLANA 6 X 38 MM KRONER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PISTOLA CON LANZA P/KARCHER K4	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	2
PISTOLA CON LANZA PARA RYOBI	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	5
PISTOLA CORTA P/HIDROLAVADORA	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	3
PISTOLA CORTA P/HIDROLAVADORA RYOBI 	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	4
PISTOLA DE IMPACTO JAMERCO JT-200	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
PISTOLA LANZA LARGA RYOBI	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	4
PISTOLA PULV CON LANZA P/KARCHER PRO HD 400	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	2
POLIPASTO ELECTRICO 400-800 KG GUTSTARK 	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
PORTA HERRAMIENTAS COMERCIAL ELECTRIC	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	3
PORTA HERRAMIENTAS TIPO RIÑONERA STANLEY	S/N	EPP	OPERACIONES	EN OPERACIÓN	1
PROBADOR DE CORRIENTE TRUPER 13989	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
PUNTAS DE IMPACTO DE CRUZ PH2 TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	6
PUNTAS MAGNETICAS PARA TALADRO 3/8 TRUPER 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	7
PUNTAS MAGNETICAS PARA TALADRO 5/16 TRUPER 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	6
PUNTAS MAGNETICAS PARA TALADRO 7/16 TRUPER	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	5
PUNTAS MAGNETICAS PARA TALADRO 8 MM	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	1
RECUPERADOR DE GAS REF EVERWELL RRU520D	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
RECUPERADOR DE GAS REF TR700 BLACK MAX	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
REGULADOR DE NITROGENO DE LATON PRECISO	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
ROLLOS PLALLOS TRANSPARENTES	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	3
ROTOMARTILLO INALAMBRICO PRETUL 26117	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
SEÑALETICA DE EXTINTORES	S/N	EQUIPOS DE SEGURIDAD	OPERACIONES	EN OPERACIÓN	1
SIERRA RECIPROCA MAKITA JR3051TK	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
SIRENA INDUSTRIAL DE SEGURIDAD 	S/N	EQUIPOS DE SEGURIDAD	OPERACIONES	EN OPERACIÓN	1
SOLDADURA DE PLATA AL 0%	S/N	MATERIAL	OPERACIONES	EN OPERACIÓN	
SOPLADOR DE AIRE 2NAIRE	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
T FLARE	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
TALADRO BOSCH GBH-2-26 DRE	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
TALADRO FIXTEC 1050 W	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
TALADRO GOXAWEE G5209 1050 W	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
TALADRO INALAMBRICO CRAFSTMAN	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
TALADRO INALAMBRICO DEWALT	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
TALADRO INALAMBRICO PRETUL	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
TALADRO INALAMBRICO RYOBI	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
TALADRO MAKITA HR1630J	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
TERMOMETRO INFRAROJO MESTEK	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
TERMOMETRO INFRAROJO UEI INF 165	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
VACUOMETRO	S/N	EQUIPO	OPERACIONES	EN OPERACIÓN	1
VALVULA DE SERVICIO 134	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	9
VALVULA DE SERVICIO R22	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	11
VALVULA DE SERVICIO R410	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
VALVULAS LATAS DE REFRIGERANTE 	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	3
HALOGEN LEAK DETECTOR	S/N	HERRAMIENTA	OPERACIONES	EN OPERACIÓN	2
`;

function parseCSV(csvText) {
  const lines = csvText.trim().split('\n');
  const headers = lines[0].split('\t');
  
  return lines.slice(1).map(line => {
    const values = line.split('\t');
    const obj = {};
    
    headers.forEach((header, index) => {
      let value = values[index]?.trim() || '';
      
      // Convertir inventario a número
      if (header === 'INVENTARIO') {
        // Manejar casos como "2 1/4" o valores vacíos
        if (!value || value === '') {
          value = 0;
        } else if (value.includes(' ')) {
          // Convierte "2 1/4" a 2.25
          const parts = value.split(' ');
          const whole = parseInt(parts[0]) || 0;
          const fraction = parts[1] ? eval(parts[1]) : 0;
          value = whole + fraction;
        } else {
          value = parseInt(value) || 0;
        }
      }
      
      obj[header.toLowerCase()] = value;
    });
    
    return obj;
  });
}

function generateSeedFile(items) {
  const itemsCode = items.map(item => {
    const inventario = typeof item.inventario === 'number' ? item.inventario : 0;
    return `    { descripcion: '${item.descripción.replace(/'/g, "\\'")}', serie: '${item.serie}', categoria: '${item.categoria}', proceso: '${item.proceso}', status: '${item.status}', inventario: ${inventario} }`;
  }).join(',\n');

  return `// src/database/seeds/items.seed.ts
import { DataSource } from 'typeorm';
import { Item } from '../../modules/catalog/items/entities/item.entity';

export async function seedItems(dataSource: DataSource) {
  const itemRepo = dataSource.getRepository(Item);

  const items = [
${itemsCode}
  ];

  // Verificar si ya existen items
  const count = await itemRepo.count();
  if (count > 0) {
    console.log('⚠️  Items ya existen en la base de datos. Skipping seed...');
    return;
  }

  // Insertar items en lotes de 100
  const batchSize = 100;
  for (let i = 0; i < items.length; i += batchSize) {
    const batch = items.slice(i, i + batchSize);
    await itemRepo.save(batch);
    console.log(\`✅ Insertados \${i + batch.length} de \${items.length} items\`);
  }

  console.log(\`🎉 \${items.length} items insertados correctamente\`);
}
`;
}

// Procesar
const items = parseCSV(csvData);
const seedContent = generateSeedFile(items);

// Guardar archivo
const outputPath = path.join(__dirname, '..', 'src', 'database', 'seeds', 'items.seed.ts');
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, seedContent);

console.log(`✅ Archivo de seed generado: ${outputPath}`);
console.log(`📊 Total de items: ${items.length}`);